window.TALAT_TAI_DEFAULT_SETTINGS = {
  currency: "THB",
  freeShippingAt: 1500,
  shippingFee: 60,
  paymentMode: "demo",
  createChargeEndpoint: "/api/payments/thai-qr",
  paymentQr: {
    thai: { label: "Thai QR", dataUrl: "", name: "" },
    myanmar: { label: "Myanmar QR", dataUrl: "", name: "" },
    crypto: { label: "Crypto Payment", dataUrl: "", name: "" },
  },
};

window.TALAT_TAI_DEFAULT_PRODUCTS = [
  {
    id: "earth-mug",
    name: { en: "Earth Glaze Mug", th: "แก้วเคลือบสีดิน", mm: "မြေသားရောင် ကြွေခွက်" },
    maker: {
      en: "Mae Rim Ceramic Studio",
      th: "สตูดิโอเซรามิกแม่ริม",
      mm: "မယ်ရိမ် ကြွေထည်စတူဒီယို",
    },
    price: 490,
    stock: 12,
    active: true,
    category: ["home", "gift"],
    badge: { en: "Bestseller", th: "ขายดี", mm: "လူကြိုက်အများဆုံး" },
    shape: "mug",
    background: "#e4c453",
    color: "#a62f27",
  },
  {
    id: "woven-tote",
    name: {
      en: "Everyday Woven Tote",
      th: "กระเป๋าสานใช้ทุกวัน",
      mm: "နေ့စဉ်သုံး ရက်လုပ်လက်ကိုင်အိတ်",
    },
    maker: {
      en: "Ban Pa Ao Weavers",
      th: "กลุ่มทอผ้าบ้านปะอาว",
      mm: "ဘန်ပါအို ရက်ကန်းအဖွဲ့",
    },
    price: 780,
    stock: 8,
    active: true,
    category: ["wear"],
    badge: { en: "New", th: "มาใหม่", mm: "အသစ်" },
    shape: "bag",
    background: "#2f6a52",
    color: "#e3b83c",
  },
  {
    id: "forest-candle",
    name: {
      en: "Forest Rain Candle",
      th: "เทียนหอมกลิ่นฝนป่า",
      mm: "တောမိုးရနံ့ ဖယောင်းတိုင်",
    },
    maker: {
      en: "Sunday Scent Lab",
      th: "ซันเดย์เซนต์แล็บ",
      mm: "ဆန်းဒေး ရနံ့စတူဒီယို",
    },
    price: 420,
    stock: 18,
    active: true,
    category: ["home", "gift"],
    badge: { en: "Small batch", th: "ผลิตจำนวนน้อย", mm: "အရေအတွက်နည်းနည်း" },
    shape: "candle",
    background: "#bc4535",
    color: "#174e3b",
  },
  {
    id: "silk-scarf",
    name: {
      en: "Sunset Silk Scarf",
      th: "ผ้าพันคอไหมสีอาทิตย์ตก",
      mm: "နေဝင်ချိန်ရောင် ပိုးပဝါ",
    },
    maker: {
      en: "Khon Kaen Silk House",
      th: "เรือนไหมขอนแก่น",
      mm: "ခွန်ကန် ပိုးထည်အိမ်",
    },
    price: 1250,
    stock: 5,
    active: true,
    category: ["wear", "gift"],
    badge: { en: "Hand dyed", th: "ย้อมมือ", mm: "လက်ဖြင့် ဆေးဆိုးထားသည်" },
    shape: "scarf",
    background: "#ead9a7",
    color: "#b9342a",
  },
];
